language: c
sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          env: CC=gcc BITS=32
        - os: linux
          env: CC=clang BITS=64
        - os: linux
          env: CC=gcc BITS=32 BACKEND=ptrace
        - os: linux
          env: CC=clang BITS=64 BACKEND=procfs
        - os: osx
          env: CC=clang BITS=32
        - os: osx
          env: CC=gcc BITS=64


before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install gcc-multilib ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ] ; then export CC=gcc-4.9 ; fi
    - $CC --version

before_script:
    - export VERBOSE=1

script:
    - mkdir -p build
    - cd build
    - CFLAGS=-m$BITS LDFLAGS=-m$BITS cmake -DBACKEND=$BACKEND ..
    - make
    - sudo make install
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then ctest --output-on-failure ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then sudo ctest --output-on-failure ; fi
