language: c
sudo: required
dist: trusty

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  global:
    - VERBOSE=1
  matrix:
    - CFLAGS=-m64 LDFLAGS=-m64
    - CFLAGS=-m32 LDFLAGS=-m32

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-multilib ;  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]; then export CC=gcc-4.9 ; fi
  - $CC --version

before_script:

script:
  - mkdir -p build
  - cd build 
  - cmake ..
  - make
  - sudo make install
  - ctest --output-on-failure
