language: c
sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          env: BITS=32 CC=gcc
        - os: linux
          env: BITS=64 CC=clang
        - os: linux
          env: BACKEND=ptrace BITS=32 CC=gcc
        - os: linux
          env: BACKEND=procfs BITS=64 CC=clang
        - os: osx
          env: BITS=32 CC=clang 
        - os: osx
          env: BITS=64 CC=gcc 


before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install gcc-multilib ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ] ; then export CC=gcc-4.9 ; fi
    - $CC --version

before_script:
    - export VERBOSE=1
    - export CFLAGS=-m$BITS
    - export LDFLAGS=-m$BITS

script:
    - mkdir -p build
    - cd build
    - cmake -DBACKEND=$BACKEND ..
    - make
    - sudo make install
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then ctest --output-on-failure ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then sudo ctest --output-on-failure ; fi
