#os: Visual Studio 2015

clone_depth: 5

init:
  - cmake -E remove c:\programdata\chocolatey\bin\cpack.exe

environment:
  matrix:
    - compiler: MinGW-w64
      platform: Win32
      prefix_dir: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
    - compiler: MinGW-w64
      platform: x64
      prefix_dir: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
    - compiler: MSVC15
      platform: Win32
    - compiler: MSVC15
      platform: x64

before_build:
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%prefix_dir%\bin;%PATH%
  - if [%COMPILER%]==[MinGW-w64] if [%PLATFORM%]==[x64]   set CFLAGS=-m64
  - if [%COMPILER%]==[MinGW-w64] if [%PLATFORM%]==[x64]   set LDFLAGS=-m64
  - if [%COMPILER%]==[MinGW-w64] if [%PLATFORM%]==[Win32] set CFLAGS=-m32
  - if [%COMPILER%]==[MinGW-w64] if [%PLATFORM%]==[Win32] set LDFLAGS=-m32
  - if [%COMPILER%]==[MinGW-w64]                          set GENERATOR="MinGW Makefiles"
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] set GENERATOR="Visual Studio 14 2015"
  - if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64]   set GENERATOR="Visual Studio 14 2015 Win64"
  - set VERBOSE=1
  - mkdir build
  - cd build

build_script:
  - cmake -G %GENERATOR% ..
  - cmake --build . --target install

after_build:
  - cmake --build . --target package

before_test:

test_script:
  - ctest --output-on-failure

artifacts:
  - path: 'build\*.zip'

deploy:
  description: 'Automatic build by CI'
  provider: GitHub
  auth_token:
    secure: jd8L5Fzd54rvILHp+UWpWjgjdb8kiI/141yAAwiHdmlkN6fEzKwPgU0yo4jj0zx0
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true        # deploy on tag push only

